### ISSUE TITLE
Add option to control whether to use `extends:` character from `listchar`

### ISSUE THREAD

**Issue by Jorenar** [rickhowe/wrapwidth#1]
Also, it would be nice to specify to use different character

**Comment by rickhowe** [comment]
Why do you need a yet another control? You can disable `list` or `extends:`.

**Comment by Jorenar** [comment]
Well, because I don't want to disable `list` nor `extends:` as I've set those for a reasons, but having window filled with that one character is very unpleasant

**Comment by rickhowe** [comment]
How about setting this script in your vimrc?
In vim , `extends` is used only when `wrap` is off, but in my plugin, it is used only when on.
So this script toggles `extends` depending on `wrap`.

```
function! s:ToggleExtendsOnWrap() abort
  if v:option_old != v:option_new
    let cw = win_getid()
    if &wrap        " remove 'extends:' from &listchars
      let lcs = split(&listchars, ',')
      let idx = match(lcs, '^extends:.\+$')
      if 0 < idx
        call setwinvar(cw, 'ext', lcs[idx])
        unlet lcs[idx]
        let &listchars = join(lcs, ',')
      endif
    else            " resume 'extends:' to &listchars
      let wv = getwinvar(cw, '')
      if has_key(wv, 'ext')
        let &listchars = (empty(&listchars) ? '' : &listchars . ',') . wv.ext
        unlet wv.ext
      endif
    endif
  endif
endfunction

augroup ToggleExtendsOnWrap
autocmd!
autocmd OptionSet wrap call s:ToggleExtendsOnWrap()
augroup NONE
```

**Comment by Jorenar** [comment]
Well, it is some solution, I guess

**Comment by rickhowe** [comment]
You would be able to set an unprintable highlight group like `Ignore` to `b:wrapwidth_hl `or `g:wrapwidth_hl` to hide `extends` char.

**Comment by Jorenar** [comment]
Yeah, great, I like it!
