### ISSUE TITLE
Text gets shifted when `linebreak` is set and pseudo-line ends at the width

### ISSUE THREAD

**Issue by Jorenar** [rickhowe/wrapwidth#10]
In the vimrc file, the settings are just `set nocp wrap linebreak`.
The wrapwidth is installed in the `~/.vim/pack/*/start` directory.

Let’s use a simple Lorem Ipsum text as an example:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
If we execute `:Wrapwidth 76`, it will look like this:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
 quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
 consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
 cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
 non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

Notice that starting from the third line, there is a space at the beginning of each line.
Now, if we navigate to the third pseudo-line, position the cursor at the beginning of “quis”, and press x, it’s not the letter ‘q’ that gets removed, but ‘u’. If we move back a character, to the supposedly empty space, and try to remove the character, it’s not the space that gets removed, but ‘q’. If we try to add some text, it will be also shifted.

**Comment by rickhowe** [comment]
Thank you for asking. I found a defect in my plugin. If you are using 3.2 wrapwidth, try to change as follows.

```
@@ -97,7 +97,8 @@
           endif
           if kt
             " find and wrap at a rightmost breakat char
-            let kx = match(tx[: bc - 2], kq, bs - 1)
+            while 0 < bc && tx[bc - 1] =~# kp | let bc -= 1 | endwhile
+            let kx = match(tx[: bc - 1], kq, bs - 1)
             if kx != -1
               let bc = kx + 1
               let vd = vc - virtcol([ln, bc], 1)[0]
```
That is a temporary fix. I think I need to check more to update the plugin.

**Comment by Jorenar** [comment]
Thanks! Seems like it does the trick

**Comment by rickhowe** [comment]
Hi, I have fixed it and updated the plugin. If it works, please close the issue.

**Comment by Jorenar** [comment]
Thanks!

There seems to still be a slight problem, but I think it's related to some other options, so I'll describe it in another ticket.
