### ISSUE TITLE
Virtual padding added as actual spaces if using `&virtualedit`

### ISSUE THREAD

**Issue by Jorenar** [rickhowe/wrapwidth#14]
As I've mentioned in #10, there is still a tiny problem, which I cornered to some interference with `&virtualedit` option.

Let's take minimal vimrc: `set wrap virtualedit=all` and the following for example:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```

With `:Wrapwidth 72`:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.
```

If you navigate to the beginning of "tempor", switch to insert mode and write, e.g. "123", this happens:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod

                                                                    123
empor incididunt ut labore et dolore magna aliqua.
```

Notice letter 't' got removed and the spaces get inserted. Those changes get written to the buffer:
```
$ cat ipsum
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod                                                                                                                                    123 empor incididunt ut labore et dolore magna aliqua.
```

**Comment by rickhowe** [comment]
Same thing happens even without the plugin. It looks like a bug in vim,

**Comment by Jorenar** [comment]
Oh, actually makes sense it would be related to any virtual text.
Do you perhaps have some minimal steps to reproduce without the plugin?

**Comment by rickhowe** [comment]
How about this?
```
call setline(1, "abcdefghijk")
call prop_type_add("test", #{highlight: "Visual"})
call prop_add(1, 7, #{type: "test", text: "<----->"})
set virtualedit=all
```
And place a cursor on 'g', and insert '123'.

Then:
`abcdef<----->      123 hijk`

**Comment by Jorenar** [comment]
Oh, not even with wrapping!
Great, thanks! I'll later report it on Vim repo.
