### ISSUE TITLE
Prevent breaking words?

### ISSUE THREAD

**Issue by josswright** [rickhowe/wrapwidth#3]
Firstly, I've been wishing for this to be an option in Vim for at least a decade (and possibly two!) so thank you so much for writing this!

I wonder if it's possible for the wrapping only to occur in whitespace, though, so that words aren't broken across the soft wrap? 

Thanks again!

**Comment by rickhowe** [comment]
Yes possible as original vim. does Try to use the `linebreak` and `breakat` options.

**Comment by josswright** [comment]
> Yes possible as original vim. does Try to use the `linebreak` and `breakat` options.

Oh, fantastic. Thanks!
