### ISSUE TITLE
TextChanged autocmd seems not to work in Neovim

### ISSUE THREAD

**Issue by delphinus** [rickhowe/wrapwidth#4]
After `Wrapwidth`, I want to wrap sentences automatically in inserting texts. For example,

```
01234567890123456789
```

With texts above, `Wrapwidth 6` makes this below.

```
012345
678901
234567
89
```

Next, I add texts but then it does not break automatically.

```
012345
678901
234678
890123456789
```

Again `Wrapwidth 6`, it makes no change. But set it with another value, such as `Wrapwidth 3`, it works again.

Is this an intended behavior?

I tried this with a minimal conf as below.

```
set runtimepath+=/path/to/wrapwidth
set wrap
```

And run it with `nvim --clean -u /path/to/minimal.vim`.

Neovim version:

```
nvim --version
NVIM v0.10.0-dev-3988+g9dc440400-Homebrew
Build type: Release
LuaJIT 2.1.1696795921
Run "nvim -V1 -v" for more info
```

**Comment by rickhowe** [comment]
I missed to check the `InsertLeave` event. Please check the version 1.3.
直っていたらクローズお願いします。

**Comment by delphinus** [comment]
Thank you. I get confirmed to be fixed.
