### ISSUE TITLE
gj movement doesn't work as expected?

### ISSUE THREAD

**Issue by arisolt** [rickhowe/wrapwidth#6]
How to reproduce:

Paste the following text in a new buffer:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Gravida dictum fusce ut placerat orci nulla. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Sed egestas egestas fringilla phasellus. Orci a scelerisque purus semper eget duis. Nibh praesent tristique magna sit amet purus. Purus in massa tempor nec feugiat nisl pretium fusce id. Pellentesque habitant morbi tristique senectus et netus. A pellentesque sit amet porttitor eget dolor. Purus gravida quis blandit turpis cursus in hac habitasse.
```

Jump back to the beginning with `gg`. Then run:
```
:set wrap | Wrapwidth 80
```

The issue is as follows:
- Movement `gj` works down to the 5th line (out of 10), then the cursor gets stuck and won't move further below that line. The 5th line actually coincides with where the displayed text would finish if only `:set wrap` is used.

Is it possible to get around this limitation?

**Comment by rickhowe** [comment]
Thank you for using the plugin. I tried your problem on vim 9.1 and nvim latest 0,10,0 with the latest wrapwidth 3.0, but I can not reproduce it and works well. Since there have been some defects in the vim's virtual text feature, I would recommend to update your vim.

**Comment by arisolt** [comment]
You're right. I was using 9.0.800. After updating to 9.1, it works as expected!

Thank you very much for writing this great plugin. I've needed this feature for a very long time!
